### ISSUE TITLE
sparrowdo bootstrap is dependable upon awk

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparrowdo#16]
Hi @Tyil 

Looking the latest changes I've  noticed this:

https://github.com/melezhik/sparrowdo/blob/master/bin/sparrowdo#L406-L417

This does not work for example at fresh Minoca OS, I guess at any OS where awk is not installed.

**Comment by Tyil** [comment]
Ah, that's annoying. I depend on `awk` in the bootstrap script since it was the easier way to go about it. `awk` itself is a [utility defined in the POSIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html), so all POSIX compliant operating systems have it. It seems Minoca is not POSIX compliant.

Right now I can see multiple resolutions to this issue:
1. Consider Minoca unsupported. This would simply mean we don't test against it and don't document it.
2. Rewrite the `awk` parts into POSIX shell. This is doable for me, and would make Minoca supported again.
3. Contact the Minoca maintainers and request them to include `awk` in the default builds. This would make Minoca more POSIX compliant (which is good in my opinion), and leaves the current bootstrap code intact.

If you have other suggestions, feel free to share. If you want the 2nd resolution, I'll start on getting that in the bootstrap script.

If you want the 3rd resolution, I could try and contact the Minoca maintainers for you, if you wish.

**Comment by melezhik** [comment]
Thanks @Tyil . I think 3-d point is the best. But it's no rush to open an issue against Minoca, I'm not sure if they use sparrowdo. I mean if they did we would definitely   ask them about tighter integration.

Reference of possible interest - https://groups.google.com/forum/#!topic/minoca-dev/WOI0jkyJyus
